language: cpp
sudo: required
os: linux
dist: xenial
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libassimp-dev
      - libx11-xcb-dev
      - libxrandr-dev 
      - libxinerama-dev
      - xorg-dev 
      - libglu1-mesa-dev
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
before_script:
  - sudo apt-get -qq update
script:
  - cmake .
  - make
notifications:
  email:
    recipients:
      - nikita.krupitskas@gmail.com
      - odintsoff@gmail.com 
    on_success: change
    on_failure: always
