version: 1.0.{build}

image: Visual Studio 2017

configuration:
  - Debug
  - Release
platform: x64
clone_folder: "c:\\UnicornEngine"
environment:
  VULKAN_SDK: "c:\\VulkanSDK\\1.0.65.1\\"
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - appveyor DownloadFile https://www.dropbox.com/s/2zwzd7vy1dy2309/VulkanSDK-1.0.65.1-Installer.exe?dl=1 -FileName vulkan-installer.exe
  - vulkan-installer.exe /S
  - rm -f vulkan-installer.exe
install:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" ..

build:
  project: "build\\Unicorn.sln"
  parallel: true
  verbosity: minimal

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%/build
  - ctest -VV -C %CONFIGURATION%

notifications:
- provider: Email
  to:
    - nikita.krupitskas@gmail.com
    - odintsoff@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
