version: 1.0.{build}

image: Visual Studio 2015

configuration:
  - Debug
  - Release
platform: x64
clone_folder: "c:\\UnicornEngine"
environment:
  VULKAN_SDK: "c:\\VulkanSDK\\1.0.39.0\\"
init:
  - appveyor DownloadFile https://vulkan.lunarg.com/sdk/download/1.0.39.0/windows/VulkanSDK-1.0.39.0-Installer.exe -FileName vulkan-installer.exe
  - vulkan-installer.exe /S
  - rm -f vulkan-installer.exe

install:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2015 Win64" ..

build:
  project: "build\\Godlike.sln"
  parallel: true
  verbosity: minimal

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%/build
  - ctest -VV -C %CONFIGURATION%

notifications:
- provider: Email
  to:
    - nikita.krupitskas@gmail.com
    - odintsoff@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
