version: 1.0.{build}

image: Visual Studio 2017

configuration:
  - Debug
  - Release
platform: x64
clone_folder: "c:\\UnicornEngine"
environment:
  VULKAN_SDK: "c:\\VulkanSDK\\1.0.42.2\\"
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - curl -fsS -o vulkan-installer.exe https://vulkan.lunarg.com/sdk/download/1.0.42.2/windows/VulkanSDK-1.0.42.2-Installer.exe?Human=true
  - vulkan-installer.exe /S
  
install:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" ..

build:
  project: "build\\Godlike.sln"
  parallel: true
  verbosity: minimal

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%/build
  - ctest -VV -C %CONFIGURATION%

notifications:
- provider: Email
  to:
    - nikita.krupitskas@gmail.com
    - odintsoff@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
